# Generated by Django 3.2.6 on 2021-08-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0001_initial'),
        ('blnk_main', '0002_auto_20210811_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banker',
        ),
        migrations.AddField(
            model_name='loan_app',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='bank_system.bank'),
        ),
    ]
