# Generated by Django 3.2.6 on 2021-08-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_main', '0003_auto_20210811_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_app',
            name='bank',
        ),
    ]
