# Generated by Django 3.2.6 on 2021-08-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_main', '0004_remove_loan_app_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_app',
            name='status',
        ),
    ]
