# Generated by Django 3.2.6 on 2021-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_main', '0005_remove_loan_app_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_app',
            name='app_type',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Fund', 'Fund'), ('Loan', 'Loan')], default='Loan', max_length=5),
        ),
    ]
