# Generated by Django 3.2.6 on 2021-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_main', '0006_auto_20210812_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Funds', 'Funds'), ('Loans', 'Loans')], default='Loans', max_length=5),
        ),
    ]
