# Generated by Django 3.2.6 on 2021-08-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blnk_main', '0004_remove_loan_app_bank'),
        ('bank_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='bank_system.bank')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blnk_main.customer')),
                ('loan_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blnk_main.loan')),
            ],
        ),
    ]
