# Generated by Django 3.2.6 on 2021-08-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0003_alter_bank_loan_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_loan',
            old_name='loan_info',
            new_name='loan',
        ),
    ]
