# Generated by Django 3.2.6 on 2021-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0004_rename_loan_info_bank_loan_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_loan',
            name='app_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
