# Generated by Django 3.2.6 on 2021-08-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0005_bank_loan_app_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_loan',
            name='app_date',
        ),
    ]
